---
title: "DataBiography"
author: "Sally Mauldin"
date: "2023-11-13"
output: html_document
---
Data Biography/Dictionary

  To understand the parameters of the project, we must define what is meant by higher education and what is not included. For the purposes of this project, higher education institutions can be understood to include four-year degree-granting colleges and universities as of 2023. The study only includes institutions that are currently operational and accredited by the Southern Association of Colleges and Schools Commission on Colleges (SACSCOC). The study will further be limited by institutions that were operational during the nineteenth century. This encompasses 22 different institutions located throughout the state. Almost all of the institutions were founded in the nineteenth century; the sole exception is the College of Charleston which traces its roots to the end of the eighteenth century. Note that College of Charleston claims 1770 as its year of founding; however, it was not chartered by the state until 1785.
  
  Higher education in the nineteenth century was complicated. Anyone reviewing this study needs to push modern thoughts of what a college or university is out of their minds. Some of these schools truly were what we would consider higher education today. Others were glorified grammar and secondary schools. Some were a mix of the two. Educational opportunities were limited in South Carolina, so I made the decision to include all schools that are currently accredited by SACSCOC to reflect that while they may have begun as something other than a traditional college, they are currently serving the purpose of a college/university as defined by modern thought.
  
  We see similar trends in historically Black colleges and universities (HBCUs). This study recognizes that HBCUs may have origins outside of what is usually thought of as college curriculum. There are several institutions that began as the equivalent of elementary and secondary schools with only a few college-tract students. Those institutions are treated as higher education institutions for the purposes of this study. They are just as important in understanding how the educational landscape unfolded as their existence points to the broader movement of Black education that “reflected the ex-slaves’ intent to restructure and control their lives.”[^fn1] Black education is an essential “lens through which to comprehend the separate and distinct social visions of a New South.”[^fn2] 
  
  Data fields that were collected include a mix of facts and texts. Facts include year of founding, enrollment numbers, land origins, location, curriculum, key figures, and endowment numbers. Texts of interest include course catalogs, newspaper articles regarding the founding and opening, legislation creating the institutions, and correspondence of key figures (such as presidents, benefactors, founders, board members, etc.). The source of these facts is varied. Most information was pulled from history books written about each individual school. Some of the information came from South Carolina history texts. Other facts were provided by the school’s website. In a few cases, none of the information I sought was available in books or online, so I reached out to the school’s archives/special collections department of the library to request assistance. I am grateful for all of the excellent help that I received from these dedicated professionals who cheerfully spent their precious time assisting a graduate student from another institution. Sources also include founding documents like charters and institutional documents like meeting minutes. These sources were obtained from the institutions via interlibrary loan as well as from archivists who assisted in researching obscure data. 
  
  In comparing the names in the dataset to historical rolls of South Carolina’s General Assembly, several names that I encountered were quite common. It was impossible to determine whether the legislator was the same person affiliated with an institution in some cases. Therefore, I made the methodological decision to err on the side of caution and not assume that they were one and the same. The list of political figures is conservative and represents the least amount of possible legislative involvement. It is possible that several nodes that appear as non-political should actually appear as a legislator. I also chose to not include some relationships in the visualization because they did not exist at the point of founding. For example, Ben Tillman served as a board member at the University of South Carolina while he was governor in the 1890s, but I did not include an edge denoting that relationship because it did not occur close to the school’s founding in 1801. Conversely, Tillman was a key figure in major decisions regarding Winthrop University close enough to the year of its founding that I chose to include that relationship. These complexities deserve further exploration, but it was a methodological choice I made to not include edges that were not in the same time period as a school’s founding.
  
  This dataset represents the beginning of a larger project, and I acknowledge that it only begins to scratch the surface of the complexities that exist in higher education. While data was collected on several different types of schools (public, religious, military, land grant, co-educational, HBCU, etc.), the time constraints of a single semester did not allow for all of those to be fully explored in this project. While there is much to discuss in this project, it is not complete as there are holes in what was included, particularly with respect to women. Future plans include exploring the papers of key figures represented in the networks as well as newspaper rhetoric about the schools and its affiliated people. I also plan to complete network visualizations comparing each school at different flashpoints in South Carolina history once the dataset is complete – Nullification Crisis, Civil War, Reconstruction, Progressive era, World War I, and the Great Depression. It is undetermined how deep into the twentieth century the larger project will go.
  
Citations

[^fn1]: James D. Anderson. The Education of Blacks in the South, 1860-1935 (Chapel Hill: University of North Carolina Press, 1988), 3.
[^fn2]: Anderson, 279.

